### ISSUE TITLE
OnClick of TimePicker Selected Time open up keyboard

### ISSUE THREAD

**Issue by pavankvch** [rheyansh/RPicker#16]
i have implemented RPicker in my App. Bug found OnClick of TimePicker Selected Time with wheel style open up keyboard.
How to prevent not to open keyboard.

**Comment by rheyansh** [comment]
Hi Pavan,

  Please add below line before calling RPicker function.
self.view.endEditing(true)

**Comment by pavankvch** [comment]
Not working, I thought this is default Behaviour for UIDatePicker.

**Comment by rheyansh** [comment]
Please share some video of flow so that it issue can be identified properly.

**Comment by rheyansh** [comment]
Closing the issue as not getting sufficient information to reproduce the issue

**Comment by Harish-Garg-259** [comment]
[https://app.screencast.com/l4YlFNazatCtq](url)
