### ISSUE TITLE
Xcode11 Not working

### ISSUE THREAD

**Issue by manohar80** [rheyansh/RPicker#5]
Please update code for swift5 and New Xcode11.its working fine for ios12 but not working in ios13.it wont work for appdelegate currentViewController.

**Comment by rheyansh** [comment]
Swift 5 compatibility, xcode 11 support, deprecations removed. Please check "swift_5" branch. Please close ticket.

**Comment by manohar80** [comment]
Thank you for your response,
I am using this picker.
