### ISSUE TITLE
Open Picker with date passed

### ISSUE THREAD

**Issue by fparkar** [rheyansh/RPicker#7]
I have date of birth field and my birth date is 12-01-2010 :)

How can I open picker with this date?

**Comment by rheyansh** [comment]
You can pass pre selected date, minimum date, maximum date like below:

let selectedDate = Date().dateByAddingYears(-6)
                let maxDate = Date()
                let minDate = Date().dateByAddingYears(-12)

                RPicker.selectDate(title: "Select", selectedDate: selectedDate, minDate: minDate, maxDate: maxDate) { [weak self] (selectedDate) in
                                    // TODO: Your implementation for date
                    self?.outputLabel.text = selectedDate.dateString("MMM-dd-YYYY")

                }


You can also pass the date picker mode too.
