### ISSUE TITLE
Background Color - Don't see the fonts If have Dark Template

### ISSUE THREAD

**Issue by ezemartinezna** [rheyansh/RPicker#8]
Hi rheyansh!

Thanks for all for this PickerView that you build.
I have detected that, if you have the Dark Theme Set up in your iPhone, I can't see the fonts.

I have a solution if I change the background color.

`datePicker.backgroundColor = UIColor.black`

How can I know if the iPhone has the Dark Theme or the Light Theme?
Regards!
Bye :)

**Comment by rheyansh** [comment]
Hi ezemartinezna,

  Thanks for your support. Dark mode support added.
